version: '3'
services:
    #nginx
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
          - ./platform/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf #map our nginx file to the default nginx file
          - ./:/var/www/html

    # php
    app:
      build:
        dockerfile: platform/php/Dockerfile
        target: "${BUILD_TARGET:-app}"
      volumes:
        - ./:/var/www/html
        - ./platform/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
#      env_file:
#      - .env
      environment:
        MYSQL_HOST: db
        MYSQL_PORT: 3306
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        REDIS_HOST: cache
        REDIS_PORT: '${REDIS_PORT}'
        XDEBUG_MODE: "${XDEBUG_MODE:-off}"

      extra_hosts:
        # Ensure that host.docker.internal is correctly defined on Linux
        - host.docker.internal:host-gateway

    # mysql
    db:
        image: 'mysql:8.0'
        ports:
          - "3306:3306"
        restart: unless-stopped
        environment:
#          MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
          MYSQL_DATABASE: '${DB_DATABASE}'
          MYSQL_PASSWORD: '${DB_PASSWORD}'
          MYSQL_USER: '${DB_USERNAME}'
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
          - 'mysqldata:/var/lib/mysql'

    # redis
    cached:
      image: redis:latest

volumes:
  mysqldata:
