name: Laravel Deployment

on:
  push:
    branches: [ "deploy-to-aws" ]
  pull_request:
    branches: [ "deploy-to-aws" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.2'
      - uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
      - name: Install Dependencies
        working-directory: ./
        run: composer install --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Execute tests via PHPUnit
        working-directory: ./
        run: vendor/bin/phpunit
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy to aws ec2
        run: ssh ${{ secrets.AWS_INSTANCE_IP }} "cd /home/source && git pull && composer install - no-dev && php artisan migrate - force && php artisan optimize"
