name: Deploy

on:
  push:
    branches: [deploy-to-aws-ec2]
  pull_request:
    branches: [deploy-to-aws-ec2]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
      - name: Install Dependencies
        working-directory: ./
        run: composer install --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Execute tests via PHPUnit
        working-directory: ./
        run: vendor/bin/phpunit
      - name: Deploy
          uses: deployphp/action@v1
          with:
            private-key: ${{ secrets.PRIVATE_KEY }}
            dep: deploy
