name: Deploy to docker hub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.2'
      - uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
      - name: Install Dependencies
        working-directory: ./
        run: composer install --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Execute tests via PHPUnit
        working-directory: ./
        run: vendor/bin/phpunit
      - run: docker build --target app -t ayenko4all/php-composer:1.1 -f ./platform/php/Dockerfile .
      - run: docker build -t ayenko4all/nginx-php:1.0 -f ./nginx/Dockerfile .
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push ayenko4all/php-composer:1.1
      - run: docker push ayenko4all/nginx-php:1.0
